---
title: "Fuel usage"
author: "pablo paulsen"
date: "01/12/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(fig.width=9, fig.height=5) 
library(dplyr)
library(ggplot2)
library(tidyr)
library(quantmod)
library(forecast)
library(tseries)
library(stringr)

```

```{r functions}

yearly_line = function(period = 12, count = 10) {
  for (i in 0:count) {
    abline(v = i*period+1, lty = 3)
  }
}
```

```{r data_setup, message = FALSE}
month_length = c(31,28,31,30,31,30,31,31,30,31,30,31)


#card transactions at fuel stations
card_fuel = read.csv("downloaded_stats/fuel_usage_card_transactions_data.csv", header = T)

#fuel cost data
fuel_cost = read.csv("downloaded_stats/MBIE_weekly_fuel_cost.csv")
fuel_cost$Week_ending_Friday = as.Date(fuel_cost$Week_ending_Friday)
fuel_cost$year = as.numeric(format(fuel_cost$Week_ending_Friday, '%Y'))
fuel_cost$month = as.numeric(format(fuel_cost$Week_ending_Friday, '%m'))

month_fuel_cost = fuel_cost %>% 
  group_by(year, month) %>% 
  summarise(petrol_cost = mean(Regular_Petrol_discounted_retail_price_NZc.p.l/100),
            diesel_cost = mean(Diesel_discounted_retail_price_NZc.p.l/100),
            premium_cost = mean(Premium_Petrol_95R_discounted_retail_price_NZc.p.l/100))

card_fuel = merge(card_fuel, month_fuel_cost, by = c("year", "month"), sort = FALSE)
card_fuel = card_fuel[card_fuel$year != 2004,]
card_fuel_bl = card_fuel[card_fuel$year <= 2019,]
#rm(fuel_cost)
#rm(month_fuel_cost)



#MBIE quaterly fuel usage data
fuel_trade = read.csv("downloaded_stats/fuel_trade.csv", header = T)
fuel_trade$qart = fuel_trade$month/3

monthly_fuel_trade = fuel_trade[rep(seq_len(nrow(fuel_trade)), each = 3), ]
monthly_fuel_trade$month = rep(1:12, length.out = nrow(monthly_fuel_trade))
monthly_fuel_trade[,c("Petrol", "Regular.Petrol", "Premium.Petrol","Diesel")] = monthly_fuel_trade[,c("Petrol", "Regular.Petrol", "Premium.Petrol","Diesel")]/3

#estimate the montly cost of trade fuel to compare to credit card transactions
monthly_trade_cost = monthly_fuel_trade[monthly_fuel_trade$year >= 2005, c("year", "month", "Regular.Petrol","Premium.Petrol", "Diesel")]
monthly_trade_cost = merge(monthly_trade_cost, month_fuel_cost, by = c("year", "month"), sort = FALSE)
monthly_trade_cost$diesel_total_cost = monthly_trade_cost$Diesel * monthly_trade_cost$diesel_cost
monthly_trade_cost$petrol_total_cost = monthly_trade_cost$Regular.Petrol*monthly_trade_cost$petrol_cost +
                                monthly_trade_cost$Premium.Petrol*monthly_trade_cost$premium_cost
monthly_trade_cost$est_total_cost = monthly_trade_cost$diesel_total_cost + monthly_trade_cost$petrol_total_cost

regional_fuel_sales = read.csv("downloaded_stats/regional_fuel_sales.csv", header = T)
regional_fuel_sales$quat = as.numeric(str_sub(regional_fuel_sales$Quarter, -1))

monthly_regional_sales = regional_fuel_sales[rep(seq_len(nrow(regional_fuel_sales)), each = 3), ]
monthly_regional_sales$month = rep(1:12, length.out = nrow(monthly_regional_sales))
#careful as using numbers as column indexs
monthly_regional_sales[,3:20] = monthly_regional_sales[,3:20]/3



                                
```


```{r fuel_decomp, warning=FALSE}
fuel_pur_series = ts((card_fuel$fuel_purchased/card_fuel$petrol)/month_length, frequency = 12)
decomp_fuel_pur = decompose(fuel_pur_series,"multiplicative")
plot(decomp_fuel_pur)
yearly_line(period = 1, count = 20)
```


```{r}
plot(decomp_fuel_pur$figure, type = 'l', main = "Seasonal component of Fuel purchases", xaxt = "n",
     xlab = "", ylab = "Change in Fuel purchases from baseline")
axis(1, labels = month.name, at = 1:12, las = 3)
```

```{r}
fuel_pur_series = ts((card_fuel$fuel_purchased)/month_length, frequency = 12)
decomp_fuel_pur = decompose(fuel_pur_series,"multiplicative")
plot(decomp_fuel_pur)
yearly_line(period = 1, count = 20)
```
```{r}
fuel_trade_cost_series = ts(monthly_trade_cost$Regular.Petrol, frequency = 12)
decomp_fuel_trade_cost = decompose(fuel_trade_cost_series, "multiplicative")
plot(decomp_fuel_trade_cost)
yearly_line(period = 1, count = 50)
```

```{r}
plot(decomp_fuel_trade_cost$figure, type = 'l', main = "Seasonal component of Fuel purchases", xaxt = "n",
     xlab = "", ylab = "Change in Fuel purchases")
points(decomp_fuel_pur$figure, type = 'l', col = "red")
legend("bottomright", legend = c("quaterly data cost estimate", "monthly card purchases"), col = 1:2, lty = 1)
axis(1, labels = month.name, at = 1:12, las = 3)
```
plot uses quarterly fuel sales averaged out to 3 month and then the monthly price of fuel and compares it to the card sales of fuel
```{r}
plot(monthly_trade_cost$est_total_cost/1e6,type = 'l', ylim = c(min(card_fuel$fuel_purchased), max(monthly_trade_cost$est_total_cost/1e6)), xaxt = "n", xlab = "", ylab = "Fuel purchases (Million $)",
     main = "Fuel Purchases")
points(card_fuel$fuel_purchased, type = 'l', col = 2)
points(y=monthly_regional_sales$Total/1e6,x = (12*10+1):(12*10+81), type = 'l', col = 3)
yearly_line(count = 20)
axis(1, labels = 2005:2021, at = c(0,1:16)*12+1, las = 3)
legend("topleft", legend = c("quaterly data cost estimate", "monthly card purchases", "regional fuel purchases"), col = 1:3, lty = 1)
```



