---
title: "Untitled"
author: "pablo paulsen"
date: "15/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=12) 
library(dplyr)
library(ggplot2)
```

```{r}
data = read.csv('Ftf Efficiency Dataset/ftf_ev_efficiency_distance_models_20211006_v1.0.csv')
data = data[-1]
head(data)
attach(data)
```

```{r}
str(data)
summary(data)
```
```{r}
data %>%
  group_by(year, month) %>% 
  summarise(count = n())

data[year == 2018 & month == 6,] %>%
  group_by(region) %>% 
  summarise(count = n()) %>% 
  arrange(-count)
```
can't really use before 2017
```{r}
mean_data = list()
for (i in 2014:2021) {
  mean_data[[i-2013]] = data[year == i,] %>% 
    group_by(month) %>% 
    summarise(mean_kwh = mean(kwh), mean_dist = mean(distance), median_kwh = median(kwh), median_dist = median(distance), mean_ef = mean(efficiency))
}
```


```{r}
par(mfrow=c(4,2))
for (i in 2014:2021) {
  par(mar = c(4, 4, 2, 4))
  cur_year = data.frame(mean_data[[i-2013]])
  plot(cur_year$month, cur_year$mean_kwh, type = 'b', main = i, xlab = "Month", ylab = "kWh", xlim = c(1,12),
       ylim = c(min(c(cur_year$mean_kwh,cur_year$median_kwh)),max(c(cur_year$mean_kwh,cur_year$median_kwh))))
  points(cur_year$month, cur_year$median_kwh, type = 'b', col = 2)
  
  
  par(new=TRUE)
  plot(cur_year$month, cur_year$mean_dist, xlab="", ylab="", xlim = c(1,12),
      ylim = c(min(c(cur_year$mean_dist,cur_year$median_dist)),max(c(cur_year$mean_dist,cur_year$median_dist))), 
      axes=FALSE, type="b", col=4)
  mtext("Distance travelled (km)",side=4,col=4,line=3, cex = 0.7) 
  axis(4, ylim=c(min(c(cur_year$mean_dist,cur_year$median_dist)),max(c(cur_year$mean_dist,cur_year$median_dist))),
      col=4,col.axis=4)
  legend("topright", legend = c("Mean KWh", "Median kWh", "Mean Distance"), col = c(1:2,4), pch = 1)

}

```
```{r Fig2, echo=TRUE, fig.height=4, fig.width=10}
ggplot(data = data[year == 2018 & month == 6,], aes(x = kwh)) + geom_density(alpha = 0.5, adjust = 1)
#ggplot(data = patient, aes(x=age))+ geom_histogram(binwidth =10, color = "peachpuff3", fill = "hotpink") + xlab("age (years)") + ggtitle("histogram of patient Age") + theme_dark() + theme(tex = element_text(size = 20))

```

```{r}
par(mfrow=c(4,2))
for (i in 2014:2021) {
  par(mar = c(4, 4, 2, 4))
  cur_year = data.frame(mean_data[[i-2013]])
  plot(cur_year$month, cur_year$mean_ef, type = 'b', main = i, xlab = "Month", ylab = "kWh", xlim = c(1,12))
  points(cur_year$month, cur_year$median_kwh, type = 'b', col = 2)
}
```
```{r Fig2, echo=TRUE, fig.height=4, fig.width=10}
ggplot(data = data[year == 2018 & month == 6,], aes(x = efficiency)) + geom_density(alpha = 0.5, adjust = 1)
```

